/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: seerW9hP5yg4q6Ka6kucWa
import {
  createStyleTokensProvider,
  createUseStyleTokens
} from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: seerW9hP5yg4q6Ka6kucWa/projectModule
import projectcss from "./plasmic.module.css"; // plasmic-import: seerW9hP5yg4q6Ka6kucWa/projectcss

const data = {
  base: projectcss.plasmic_tokens,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  data,
  _useGlobalVariants
);
