/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: seerW9hP5yg4q6Ka6kucWa
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsqO7IevvmIhf5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qO7IevvmIHF5/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsqO7IevvmIhf5
});
